# Generated by Django 6.0.5 on 2026-06-07 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('ville', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('secteur', models.CharField(blank=True, max_length=100)),
                ('verified', models.BooleanField(default=False)),
                ('email_verified', models.BooleanField(default=False)),
                ('verification_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email_verified', models.BooleanField(default=False)),
                ('verification_code', models.CharField(blank=True, max_length=10, null=True)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiants', to='webterminal.ecole')),
            ],
        ),
        migrations.CreateModel(
            name='EquipeStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipes_stage', to='webterminal.entreprise')),
                ('etudiants', models.ManyToManyField(blank=True, related_name='equipes_stage', to='webterminal.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupes', to='webterminal.ecole')),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('reunion', 'Réunion'), ('entretien', 'Entretien'), ('deadline', 'Deadline'), ('autre', 'Autre')], max_length=20)),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('lieu', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='planifie', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ecoles', models.ManyToManyField(blank=True, related_name='evenements', to='webterminal.ecole')),
                ('entreprises', models.ManyToManyField(blank=True, related_name='evenements', to='webterminal.entreprise')),
                ('equipes_stage', models.ManyToManyField(blank=True, related_name='evenements', to='webterminal.equipestage')),
                ('etudiants', models.ManyToManyField(blank=True, related_name='evenements', to='webterminal.etudiant')),
                ('groupes', models.ManyToManyField(blank=True, related_name='evenements', to='webterminal.groupe')),
            ],
        ),
        migrations.AddField(
            model_name='etudiant',
            name='groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etudiants', to='webterminal.groupe'),
        ),
    ]
