# Generated by Django 6.0.5 on 2026-06-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webterminal', '0002_administrateur_evenement_createur_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecole',
            name='email',
            field=models.EmailField(default=0, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ecole',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ecole',
            name='password',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ecole',
            name='verification_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ecole',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ecole',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
