# Generated by Django 6.0.5 on 2026-06-10 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
